# Generated by Django 5.1.3 on 2024-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='settings_name', max_length=200)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
